version: "3"
services:
  app:
    container_name: shopping-cart-web
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: shopping-cart-db
    image: mongo
    ports:
      - 27017:27017
